var icici={
  "name":"ICICI",
  "logo":"assets/personalLoan/icici.png",
 "logo2":"assets/personalLoan/3a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan Apply Online Now and Get Instant",
  "amount":"50000-20Lacs",
  "maxamount":"20Lacs",
  "tenure":"12-60",
  "interest":"11.20%",
  "processing fee":"0",
  "eligibility":"salary 30000,2 years job experience",
  "documents":"KYC documents, income proof, passport size photo",
  "repayment":"eNACH",
  "earlyrepayment":"5% of outstanding principal amount",
  "overdue":"Overdue Rule As per company policy",
  "loandisbursal":"Customer's salary a/c",
};
var tata_capital={
  "name":"TATA CAPITAL",
  "logo":"assets/personalLoan/17.png",
  "logo2":"assets/personalLoan/17a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan. Apply Online Now and Get Instant",
  "amount":"1 Lac-25Lacs",
  "maxamount":"25Lacs",
  "tenure":"1-6",
  "interest":"10.99%",
  "processing fee":"0",
  "eligibility":"Salary of 15000,1 year of job continuty.",
  "documents":"Application Form, KYC, Salary Slip and Bank Statement",
  "repayment":"From the customer's salary account",
  "earlyrepayment":"Zero charges on Part Pre-Payment",
  "overdue":"Overdue Rule As per company policy",
  "loandisbursal":"AS PER THE POLICY",

};
var Money_view={
  "name":"Money View",
  "logo":"assets/personalLoan/14.png",
   "logo2":"assets/personalLoan/14.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan. Apply Online Now and Get Instant",
  "amount":"1 Lac-25Lacs",
  "maxamount":"25Lacs",
  "tenure":"1-6",
  "interest":"10.99%",
  "processing fee":"0",
  "eligibility":"Salary of 15000,1 year of job continuty.",
  "documents":"Application Form, KYC, Salary Slip and Bank Statement",
  "repayment":"From the customer's salary account",
  "earlyrepayment":"Zero charges on Part Pre-Payment",
  "overdue":"Overdue Rule As per company policy",
  "loandisbursal":"AS PER THE POLICY",

};
//var Chintamani_Finlease={
//  "name":"Chintamani Finlease",
//  "logo":"assets/personalLoan/17.png",
//  // "logo2":"assets/BusinessLoan/1a.png",
//  "desc":"Get Attractive Rates on ICICI Bank Personal Loan.\n Apply Online Now and Get Instant",
//  "amount":"50,000-2Lacs",
//  "maxamount":"25Lacs",
//  "tenure":"12-15",
//  "interest":"26.00%",
//  "processing fee":"2.5%-5%",
//  "eligibility":"Indian resident - Salaried only",
//  "documents":"PAN Card, Aadhaar Card, Salary Slip -3, Banking 6 month",
//  "repayment":"NACH",
//  "earlyrepayment":"As per Policy",
//  "overdue":"As per Policy",
//  "loandisbursal":"transfer to borrower bank account - NEFT/RTGS",
//
//};
//var Eloan_Personal_Loan={
//  "name":"Eloan Personal Loan",
//  "logo":"assets/personalLoan/17.png",
//  // "logo2":"assets/BusinessLoan/1a.png",
//  "desc":"Get Attractive Rates on ICICI Bank Personal Loan. Apply Online Now and Get Instant",
//  "amount":"3Lacs-50Lacs",
//  "maxamount":"25Lacs",
//  "tenure":"3-5",
//  "interest":"11.00%",
//  "processing fee":"1.25%-2%",
//  "eligibility":"Own/ Family Owned residence required. Min Salary 35000, Location: Delhi NCR only. CIBIL > 650",
//  "documents":"Pan Card, Adhaar Card, Ownership proof, 3 months’ salary slip, 6 months banking in PDF",
//  "repayment":"By ECS from salary account",
//  "earlyrepayment":"0% - 3% Foreclosure charges depending on bank",
//  "overdue":"As per Policy",
//  "loandisbursal":"Directly to salary account",
//
//};
var Qbera={
  "name":"Qbera",
  "logo":"assets/personalLoan/4.png",
  "logo2":"assets/personalLoan/4a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan. Apply Online Now and Get Instant",
  "amount":"1Lac-15Lacs",
  "maxamount":"15Lacs",
  "tenure":"12-60",
  "interest":"12.00%",
  "processing fee":"1%-4%",
  "eligibility":"Locations: 180 Cities; Age: 23-57 Years\nIncome: 20,000+ Net Take Home\nCIBIL 600+& thin file, NTC\nEmployer Type: Any Active Public Ltd., Pvt. Ltd, Govt, LLP, Proprietorship & Partnership with Vintage >=2 Years\nSalary Method & Dates: No Cash Salary Allowed\nDates to be +/- 7 days every month\nFOIR: 20-35k: 50%, 35-50k: 65%, 50K+: 70%\nAccommodation Type: All (Rented, Bachelor, PG, Company Accommodation, Hostel, Owned, etc.)\n",
  "documents":"PAN, current/permanent address proof, selfie, cancelled cheque",
  "repayment":"Monthly EMI",
  "earlyrepayment":"Varies between lenders",
  "overdue":"Varies between lenders",
  "loandisbursal":"Directly to salary account",

};

var Retra={
  "name":"Retra",
  "logo":"assets/personalLoan/icon.png",
  "logo2":"assets/personalLoan/icon.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get Instant",
  "amount":"50,000-10Lacs",
  "maxamount":"25Lacs",
  "tenure":"6-48",
  "interest":"20.00%",
  "processing fee":"2%",
  "eligibility":"Minimum salary: 18K net per month; minimum age: 21 years",
  "documents":"3-month salary slip, 6-month bank statement",
  "repayment":"NACH - monthly repayment",
  "earlyrepayment":"No prepayment for first 6 months",
  "overdue":"DPD basis EMI being missed on the due date",
  "loandisbursal":"Agreement, KYC",

};
var Lendbox={
  "name":"Lendbox",
  "logo":"assets/personalLoan/5.png",
   "logo2":"assets/personalLoan/5a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan. Apply Online Now and Get In",
  "amount":"510,000-10Lacs",
  "maxamount":"10Lacs",
  "tenure":"3-36",
  "interest":"12.00%",
  "processing fee":"2%-5%",
  "eligibility":"Min Salary - 20,000. Bank Credit mandatory.",
  "documents":"PAN, Aadhar, Bank Statement (6 months), Salary slips (3)",
  "repayment":"NACH (auto-debit)",
  "earlyrepayment":"No prepayment charges after 3 EMIs Upwards",
  "overdue":"",
  "loandisbursal":"",

};
var Upwards={
  "name":"Upwards",
  "logo":"assets/personalLoan/22.png",
  "logo2":"assets/personalLoan/22a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan. Apply Online Now and Get In",
  "amount":"20,000-2Lacs",
  "maxamount":"2Lacs",
  "tenure":"6-24",
  "interest":"18.00%",
  "processing fee":"2%",
  "eligibility":"Salaried (Minimum Rs 17000/month Net-in-hand); Cash salary not eligible",
  "documents":"Photo, PAN, Aadhar, latest Salary slip and 3 months’ bank statement",
  "repayment":"Via Nach and Auto debit",
  "earlyrepayment":"Allowed post payment of 1 EMI. Charges are 5% of principal outstanding at the time of foreclosure",
  "overdue":"Rs 550 Bounce charges + 3% Penal Interest",
  "loandisbursal":"Direct to customer bank account",

};
//var Loanwalle={
//  "name":"Loanwalle",
//  "logo":"assets/personalLoan/17.png",
//  // "logo2":"assets/BusinessLoan/1a.png",
//  "desc":"Get Attractive Rates on ICICI Bank Personal Loan. Apply Online Now and Get In",
//  "amount":"5,000-1Lac",
//  "maxamount":"1Lacs",
//  "tenure":"3-12",
//  "interest":"0.10%/perDay",
//  "processing fee":"₹ 900",
//  "eligibility":"Salaried Customer with Salary of More than 10k per month.",
//  "documents":"Pan Card, Adhar Card, Last 2 Months salary slip, Last three months Updated Bank Statement and Cheque.",
//  "repayment":"Via Nach and Auto debit",
//  "earlyrepayment":"Allowed post payment of 1 EMI. Charges are 5% of principal outstanding at the time of foreclosure",
//  "overdue":"Rs 550 Bounce charges + 3% Penal Interest",
//  "loandisbursal":"Direct to customer bank account",
//
//};
//
var CASHe={
  "name":"CASHe",
  "logo":"assets/personalLoan/2.png",
  "logo2":"assets/personalLoan/2.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get In",
  "amount":"9,000-3Lacs",
  "maxamount":"3Lacs",
  "tenure":"2-12",
  "interest":"30.00%",
  "processing fee":"0",
  "eligibility":"Salaried employees with a Min net salary of 15K per month",
  "documents":"PAN, Salary Slip, Bank Statement and Address Proof",
  "repayment":"NEFT, UPI, Debit Card, Net banking",
  "earlyrepayment":"Monthly Interest Payable, No Prepayment Fees",
  "overdue":"Penalty charges",
  "loandisbursal":"Salary Bank Account",

};
var Muthoot={
  "name":"Muthoot",
  "logo":"assets/personalLoan/21.png",
   "logo2":"assets/personalLoan/21.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get In",
  "amount":"50,000-15Lacs",
  "maxamount":"15Lacs",
  "tenure":"1-5(Year)",
  "interest":"14.00%",
  "processing fee":"0",
  "eligibility":"Subject to credit verification, eligibility calculation(Qualifying criteria shared in PDF)",
  "documents":"Photo, Signature Proof, Address Proof, Employment Proof, Company Identity,3 M Payslips,6M Salary Credit Banking",
  "repayment":"",
  "earlyrepayment":"",
  "overdue":"",
  "loandisbursal":"Into Salary Account",

};

var OYE_Loans={
  "name":"OYE Loans",
  "logo":"assets/personalLoan/6.png",
  "logo2":"assets/personalLoan/6a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get In",
  "amount":"10,000-1Lac",
  "maxamount":"1Lacs",
  "tenure":"12",
  "interest":"18.00%",
  "processing fee":"3%+GST",
  "eligibility":"Minimum monthly salary of 15000, directly deposited in Bank",
  "documents":"PAN, Aadhaar, Current Address Proof (if different), Employment Proof, Bank Statement (3 months)",
  "repayment":"12 EMIs",
  "earlyrepayment":"Zero charges",
  "overdue":"Default / late payment fee of 1% + GST of the outstanding principal balance or INR 500",
  "loandisbursal":"",

};
var NIRA={
  "name":"NIRA",
  "logo":"assets/personalLoan/1a.png",
   "logo2":"assets/personalLoan/1a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n Loan. Apply Online Now and Get In",
  "amount":"5,000-1Lac",
  "maxamount":"1Lacs",
  "tenure":"3-12",
  "interest":"36.00%",
  "processing fee":"0",
  "eligibility":"CIBIL >681, Salaried with salary > 12000 per month take home",
  "documents":"3m bank statement, 3m salary slip, aadhar",
  "repayment":"as per policy",
  "earlyrepayment":"first 3 months chargeable @ 2.5% of loan amount, no charges after",
  "overdue":"as per policy",
  "loandisbursal":"in bank account",

};
var Indialends_Personal_Loan={
  "name":"Indialends Personal Loan",
  "logo":"assets/personalLoan/7.png",
  "logo2":"assets/personalLoan/7a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get In",
  "amount":"1Lac-10Lacs",
  "maxamount":"25Lacs",
  "tenure":"12-60",
  "interest":"15.00%",
  "processing fee":"0",
  "eligibility":"Bureau Score >=750, No Derogs, Not Currently Overdue, Salary>25k, City Pin codes:\n (110,121,122,141,160,201,226,302,342,360,380,394,395,400,401,410,411,421,440,441\n,492,500,520,521,530,560,600,700)",
  "documents":"For Self-Employed Individuals\n1. Identity & Age Proof \n2. Completely filled personal loan application with photograph\n3. PAN Card \n4. Residence proof - Passport driving licence, Voter ID, post-paid/landline bill, utility bills (electricity/water/gas)\n5. Bank statements for the last 3 months(preferably your salary account) \n6. Salary Slips of last 3 months\n7. Last 3 years Income Tax Returns with computation of Income\n8. Last 3 years CA Certified / Audited Balance Sheet and Profit & Loss Account\nFor Salaried Individuals \n1. Identity & Age Proof \n2. Completely filled personal loan application with photograph \n3. PAN Card\n4. Residence proof - Passport driving licence, Voter ID, postpaid/landline bill, utility bills (electricity/water/gas)\n5. Bank statements for the last 3 months(preferably your salary account) \n6. Salary Slips of last 3 months\n7. Form 16 or Income Tax Returns of last 3 years\n",
  "repayment":"On lender basis",
  "earlyrepayment":"",
  "overdue":"On lender basis",
  "loandisbursal":"",

};
var PhoneParLoan={
  "name":"PhoneParLoan",
  "logo":"assets/personalLoan/18.png",
   "logo2":"assets/personalLoan/18a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n  Loan. Apply Online Now and Get In",
  "amount":"10,000-5Lacs",
  "maxamount":"5Lacs",
  "tenure":"2-48",
  "interest":"2.00%",
  "processing fee":"2.5%-4%",
  "eligibility":"age>21, salary>8K",
  "documents":"Address Proof, Identity Proof, Income, Bank Statement, Signature (PAN card, Offline addhar verification, salary slip/ITR, selfie,\n signature)",
  "repayment":"",
  "earlyrepayment":"",
  "overdue":"",
  "loandisbursal":"",

};
var Paysense={
  "name":"Paysense",
  "logo":"assets/personalLoan/8.png",
   "logo2":"assets/personalLoan/8a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n  Loan. Apply Online Now and Get In",
  "amount":"5,000-5Lacs",
  "maxamount":"5Lacs",
  "tenure":"3-60",
  "interest":"19.20%",
  "processing fee":"3.5%+18%GST",
  "eligibility":"Resident of India\nAge: 21 years to 60 years\nEmployment Type: Salaried and Self-employed \nMinimum Monthly Income: ₹ 12,000 for salaried and ₹ 15,000 for self-employed \nLocation: We are active in 40+ cities.",
  "documents":"Selfie, Permanent & current address proof, PAN, Aadhaar, bank statement 3 months + current month, bank details",
  "repayment":"3rd of every month - static date",
  "earlyrepayment":"",
  "overdue":"Penalty according to days past due",
  "loandisbursal":"Valid bank account in your name",

};
var Faircent={
  "name":"Faircent",
  "logo":"assets/personalLoan/10.png",
  "logo2":"assets/personalLoan/10a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n  Loan. Apply Online Now and Get In",
  "amount":"50,000-10Lacs",
  "maxamount":"10Lacs",
  "tenure":"2-36",
  "interest":"9.96%",
  "processing fee":"2.5%",
  "eligibility":"Indian resident (18-55 years old)",
  "documents":"Pan Card\n Income documents\n address proof\n (Aadhar, utility bills, passport, etc.)\n",
  "repayment":"NACH, Payment gateway (UPI, net banking, debit card, paytm)",
  "earlyrepayment":"No prepayment charges after first three EMIs",
  "overdue":"penal interest 18%",
  "loandisbursal":"",

};
var Avail_Finance={
  "name":"Avail Finance",
  "logo":"assets/personalLoan/9.png",
   "logo2":"assets/personalLoan/9a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get In",
  "amount":"5,000-40,000",
  "maxamount":"₹ 40,000",
  "tenure":"2-8",
  "interest":"24.00%",
  "processing fee":"₹600",
  "eligibility":"Income>8,000 \nCIBIL > 600 \nJob Tenure minimum 6 months",
  "documents":"Bank Statement (6 months) \nCurrent Address Proof \nPermanent address proof\n Salary Slip (3 months) \nPAN CARD \nAadhar Card\n",
  "repayment":"Monthly",
  "earlyrepayment":"No prepayment penalty",
  "overdue":"Zero overdue in last 3 months",
  "loandisbursal":"",

};
var Payme_India={
  "name":"Payme India",
  "logo":"assets/personalLoan/11.png",
   "logo2":"assets/personalLoan/11a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal\n  Loan. Apply Online Now and Get In",
  "amount":"10,000-2Lacs",
  "maxamount":"2Lacs",
  "tenure":"3-12",
  "interest":"1.00%",
  "processing fee":"Rs 300/- OR 3% of disburse amount- whichever is higher(GST Included)",
  "eligibility":"Indian Resident (25 to 52 Years old)",
  "documents":"Pan Card, Aadhar Card, and Last 3-month salary account bank statement ",
  "repayment":"Mandate, and NACH ",
  "earlyrepayment":"No pre closure charges ",
  "overdue":"Penal interest rises upto 0.7% per day\n and Late fees of Rs 500/- OR 3% of disburse amount-\n which ever is higher",
  "loandisbursal":"Salary bank account ",

};
var Early_Salary={
  "name":"Early Salary",
  "logo":"assets/personalLoan/12.png",
  "logo2":"assets/personalLoan/12a.png",
  "desc":"Get Attractive Rates on ICICI Bank Personal \n Loan. Apply Online Now and Get In",
  "amount":"8,000-2Lacs",
  "maxamount":"2Lacs",
  "tenure":"3-12",
  "interest":"24%",
  "processing fee":"299/- Rs",
  "eligibility":"Salary Account Transfer, Salary minimum 18k, Age 21-50, Operational City only",
  "documents":"Government ID or Address proof, PAN Card",
  "repayment":"Auto debit or customer can pay through app",
  "earlyrepayment":"Not exceeding 2% of the Prepaid Amount. But rejoice! Currently, we don't charge for prepayment.",
  "overdue":"1) In case of delay in payment of Amount Due, we will charge a late payment fee not exceeding 3% per month on the\n amount due, subject to minimum of Rs. 500. (2)In case of default by reason of the Repayment Instrument(s) \n being dishonoured, Early Salary will charge Rs. 500/- per month / per default towards its dishonour. (3) Overdue \n interest will be charged at 30% p.a. on total overdue amount on a daily basis. Overdue balance means principal \n outstanding and due interest.",
  "loandisbursal":null,

};

var PersonalLoans=[
  icici,tata_capital, Early_Salary,Payme_India, Avail_Finance,Faircent,Paysense,PhoneParLoan,Indialends_Personal_Loan,
  NIRA,OYE_Loans,Muthoot,CASHe,Upwards, Lendbox,Retra, Qbera,Money_view
];
