var indifi={
  "name":"Indifi",
  "logo":"assets/BusinessLoan/1.png",
  "logo2":"assets/BusinessLoan/1a.png",
  "desc":"Indifi is a Non-Banking Financial\n Company (NBFC)that offers business loans\n to Small and Medium Size Enterprises \n(SMEs)at an interest rate of 22% onwards. ",
  "amount":"25lacs-50Lacs",
  "maxamount":"50Lacs",
  "maxamount1":"50Lacs",
  "tenure":"12-36",
  "interest":"18.00%",
  "processing fee":"2%",
  "eligibility":"Mon operational history 1 year \n 2 years ITR for more than Rs. 10 Lakh",
  "documents":"KYC Details, Address Proof,\nBusiness Proof\nLatest Banking required for 6 months",
  "repayment":null,
  "earlyrepayment":null,
  "overdue":null,
  "loandisbursal":null,
};

var lendingkart={
  "name":"LendingKart",
  "logo":"assets/BusinessLoan/2.png",
  "logo2":"assets/BusinessLoan/2a.png",
  "desc":"The fastest and easiest\n way to get a business loan",
  "amount":"50,000-50Lacs",
  "maxamount":"50Lacs",
  "maxamount1":"50Lacs",
  "tenure":"6-36",
  "interest":"18.00%",
  "processing fee":"2%",
  "eligibility":"Age 21 - 60 Years\n >2 Lakh Monthly Sales \nBusines Vintage>=2 years for\n Residence - Rented,Office-Rented\n Business Vintage>=1year for all\nother cases\n Servicable Pin Code List(PFA)\n Must have Business Registration Proof\n We dont accept saving A/c",
  "documents":null,
  "repayment":"To Borrowers Account",
  "earlyrepayment":"No Prepayment charges after 1st\nEMI. Only full prepayment possible.",
  "overdue":null,
  "loandisbursal":null,


};
var aditya={
  "name":"ADITYA BIRLA",
  "logo":"assets/BusinessLoan/3.png",
  "logo2":"assets/BusinessLoan/3a.png",
  "desc":"Our customized financing solutions\n enable you to meet all your business \nneeds and realize your ambitions.",
  "amount":"1Lac-20Lacs",
  "maxamount":"50Lacs",
  "maxamount1":"50Lacs",
  "tenure":"12-60",
  "interest":"18.00%",
  "processing fee":"\u20b9 0",
  "eligibility":"Self Emplyed Individuals,\nPartnership Firm, Pvt.Ltd,\nCompanies",
  "documents":"KYC Details, Address Proof,\nBusiness Proof\nLatest Banking required for 6 months",
  "repayment":"ENACH",
  "earlyrepayment":"AS PER POLICY",
  "overdue":"AS PER POLICY",
  "loandisbursal":"In Bank Account",
};
var eloan={
  "name":"Eloan Business Loan",
  "logo":"assets/BusinessLoan/4.png",
  "logo2":"assets/BusinessLoan/4a.png",
  "desc":"One Stop shop for comparing loan offers from\nvarious banks/instituitions, door step service\nfrom one of the oldest distribution firm\nin India",
  "amount":"10Lac-1Cr",
  "maxamount":"1Cr",
  "maxamount1":"100Lacs",
  "tenure":"1-03",
  "interest":"15.50%",
  "processing fee":"2%",
  "eligibility":"Calculated as per tax returns\nProfit&Loss acccounts,\nTentatively loan amount is 2.5\n times of the annual income incase of\n SENP profiles.\nThere are other products like\nbanking surrogate for SEND\ncustomers where income is not a criteria",
  "documents":"As per link on out Website",
  "repayment":"Through ECS7 Direct Debit",
  "earlyrepayment":"NILL Penalty on variable loans,\nin case of FIXED loans penalty is\n there in business entity on loan",
  "overdue":null,
  "loandisbursal":null,
};
var fintree={
  "name":"Fintree",
  "logo":"assets/BusinessLoan/5.png",
  "logo2":"assets/BusinessLoan/5a.png",
  "desc":"Loan against Digital payments,which is a\n short-term facility extended to merchants who\nhave a Point -Of-Sale (POS)machine installed at their premises.\nAlternatively for merchants without POS machines we enable the\ncredit facility based on their business banking. ",
  "amount":"1Lac-10Lacs",
  "maxamount":"10Lac",
  "maxamount1":"10Lacs",
  "tenure":"1-02",
  "interest":"18.00%",
  "processing fee":"2%",
  "eligibility":"POS Should be there,\nBusiness Vintage- Minimum 1 Year,\nPOS Vintage- Minimum 6 Months,\nAverage Swipe- 1lakh Per Month",
  "documents":"KYC (Individual + Business),\nbusiness banking, Applicabale \nstatutary Licenses.",
  "repayment":"Though POS machine / NACH payments\nthrough business bank account",
  "earlyrepayment":"Equated Daily Installments (EDI)",
  "overdue":"Overdue interest / NACH bounce\ncharges as applicable.",
  "loandisbursal":null,
};
var ziploan={
  "name":"ZIPLOAN",
  "logo":"assets/BusinessLoan/6.png",
  "logo2":"assets/BusinessLoan/6a.png",
  "desc":"Minimal Documentation",
  "amount":"1Lac-5Lacs",
  "maxamount":"5Lac",
  "maxamount1":"5Lacs",
  "tenure":"1-02",
  "interest":"23.00%",
  "processing fee":"2-3%",
  "eligibility":"Minimum Banking turnover for\ntrader Rs.15lakh. Minimum\nbanking turnover for\nManufacturer&Service 10Lac",
  "documents":"2 Years ITRS Required",
  "repayment":"Repayment through NACH. No\nhassle of cash collection",
  "earlyrepayment":null,
  "overdue":null,
  "loandisbursal":"Bank Account",
};
var loansimple={
  "name":"Loan Simple for Business",
  "logo":"assets/BusinessLoan/7.png",
  "logo2":"assets/BusinessLoan/7a.png",
  "desc":"Get small business loans for MSMEs in Delhi\nNCR in just 48hrs.",
  "amount":"10,000-5Lacs",
  "maxamount":"5Lacs",
  "maxamount1":"5Lacs",
  "tenure":"3-12",
  "interest":"19.92%",
  "processing fee":"3%",
  "eligibility":"Atleast one year old business\n2+ lakhs monthly revenue",
  "documents":"PAN Adhaar,6 or 12months bank\nsatement or \n E-wallet statement",
  "repayment":"Daily Repayment",
  "earlyrepayment":null,
  "overdue":null,
  "loandisbursal":null,
};
var shriram={
  "name":"Shriram",
  "logo":"assets/BusinessLoan/8.png",
  "logo2":"assets/BusinessLoan/8a.png",
  "desc":"Shriram City Union Finance offers customized\nbusiness loans to SMEs",
  "amount":"5Lacs-50Lacs",
  "maxamount":"50Lac",
  "maxamount1":"50Lacs",
  "tenure":"18-35",
  "interest":"18.00%",
  "processing fee":"\u20b9 0",
  "eligibility":"Atleast two years old business\nBusiness registration certificate,\nminimum tenure -12months. Valid\nidentity proof & address proof",
  "documents":null,
  "repayment":null,
  "earlyrepayment":null,
  "overdue":null,
  "loandisbursal":null,
};

var b2c={
  "name":"Bridge2Capital",
  "logo":"assets/BusinessLoan/9.png",
  "logo2":"assets/BusinessLoan/9a.png",
  "desc":"Non-bank Liquidity platform for small\nbusinesses in small cities",
  "amount":"50,000-5Lacs",
  "maxamount":"5Lac",
  "maxamount1":"5Lacs",
  "tenure":"2-05",
  "interest":"27.00%",
  "processing fee":"2%",
  "eligibility":"As per U/W protocols of xtracap",
  "documents":"Adhaar/Pan/Bank\nStatement/GST cert",
  "repayment":"Weekly/Fortnightly",
  "earlyrepayment":"No prepayment changes",
  "overdue":"500 penalty and\npenal interest",
  "loandisbursal":"Suppliers account",
};

var arthan={
  "name":"Arthan Finance",
  "logo":"assets/BusinessLoan/10.png",
  "logo2":"assets/BusinessLoan/10a.png",
  "desc":"Offering Business Loans to Small\n and Micro Businesses",
  "amount":"1Lac-20Lacs",
  "maxamount":"20Lac",
  "maxamount1":"20Lacs",
  "tenure":"2-07",
  "interest":"24.00%",
  "processing fee":"\u20b9 0",
  "eligibility":"Minimum Business Vintage-2 years,\nMin age=21+ years,income\nDocuments suggesting cash\nflows,in case of Loan\ncollateral such asconstructed properties\nand LIC",
  "documents":"KYC of Firm and\nIndividuals,Vintage proof,Bank\nStatement,Income Documents\nand Collateral Documents",
  "repayment":"EMI",
  "earlyrepayment":null,
  "overdue":"36% PA",
  "loandisbursal":"NEFT/RTGS to customers account",
};

var fino={
  "name":"Fino Finance",
  "logo":"assets/BusinessLoan/11.png",
  "logo2":"assets/BusinessLoan/11a.png",
  "desc":"Fino Finance Private Limited\n(Formerly Intrepid Finance and Leasing Private Limited) is a\nnon-deposit taking NBFC-MFI registered\nwith RBI. ",
  "amount":"50,000-1Lac",
  "maxamount":"1Lac",
  "maxamount1":"1Lacs",
  "tenure":"12",
  "interest":"35.00%",
  "processing fee":"3% of Loan amount + GST",
  "eligibility":"Self-employed with business vintage of more than three years",
  "documents":null,
  "repayment":"Nach",
  "earlyrepayment":null,
  "overdue":null,
  "loandisbursal":"Bank account",
};




var businessLoans=[
  indifi,lendingkart,aditya,eloan,fintree,ziploan,loansimple,shriram,b2c,arthan,fino
];
